from turtle import*
from random import*

speed(0)

for i in range(20):
    penup()
    goto(randint(-500, 500), randint(-300,300))
    for i in range(8):
        for i in range(1):
            pendown()
            begin_fill()
            color("navy")
            fd(20)
            lt(59)
            fd(56)
            rt(59)
            end_fill()
            penup()
            rt(45)
            for i in range(2):
                pendown()
                begin_fill()
                color("light blue")
                fd(20)
                rt(59)
                fd(56)
                lt(59)
                end_fill()
                penup()
                #goto(randint(-500, 500), randint(-300,300))
                rt(45)

                pendown()
                begin_fill()
                color("navy")
                fd(20)
                lt(59)
                fd(56)
                rt(59)
                end_fill()
                penup()
                #setposition(0,0)
                rt(45)
                penup()
                goto(randint(-500, 500), randint(-300,300))

                for i in range(8):
                    for i in range(1):
                        pendown()
                        begin_fill()
                        color("purple")
                        fd(20)
                        lt(59)
                        fd(56)
                        rt(59)
                        end_fill()
                        penup()
                        rt(45)
                        for i in range(8):
                            pendown()
                            begin_fill()
                            color("pink")
                            fd(20)
                            rt(59)
                            fd(56)
                            lt(59)
                            end_fill()
                            penup()
                            #setposition(-100,100)
                            rt(45)

                            pendown()
                            begin_fill()
                            color("purple")
                            fd(20)
                            lt(59)
                            fd(56)
                            rt(59)
                            end_fill()
                            penup()
                            #setposition(-100,100)
                            rt(45)
